name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install Criterion
      run: sudo add-apt-repository ppa:snaipewasataken/ppa && sudo apt-get update && sudo apt-get install criterion-dev
    - name: make tests_clean
      run: make tests_clean
