name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install Criterion
      run: sudo add-apt-repository ppa:snaipewastaken/ppa && sudo apt-get update && sudo apt-get install criterion-dev
    - name: install build-essential gcovr gcc
      run: sudo apt-get install -y gcovr build-essential gcc
    - name: make tests
      run: make tests
